i18n.setDefaultLanguage('en_GB');

i18n.showMissing(true);

if (Meteor.isClient && (Meteor.settings == null)) {
Meteor.settings = {};
}

if (Meteor.settings["public"] == null) {
Meteor.settings["public"] = {};
}

var supportedHDWallets = [
  {
    type: 'bitcoin-wallet',
    label: 'Bitcoin Wallet (mobile)'
  }, {
    type: 'electrum2',
    label: 'Electrum (2.x)'
  }, {
    type: 'electrum',
    label: 'Electrum (<2.0)'
  }, {
    type: 'armory',
    label: 'Armory'
  }, {
    type: 'trezor',
    label: 'Trezor'
  }, {
    type: 'mycelium',
    label: 'Mycelium'
  }
];


Meteor.settings["public"].coyno = {
  allowedCurrencies: ['EUR', 'USD', 'BTC', 'XRP', 'Altcoin'],
  valuedCurrencies: ['EUR', 'USD', 'BTC'],
  fiatCurrencies: ['EUR', 'USD'],
  defaultJurisdiction: 'de',
  allowedNodeTypes: ['exchange', 'bankaccount', 'bitcoinwallet'],
  supportedExchangeTypes: ['coinbase'],
  availableExchanges : [
    {
      type: 'coinbase',
      label: 'Coinbase',
      url: "https://www.coinbase.com/oauth/authorize?client_id=9263955262f41843c0f4f1038311d0781cfaf442d4654b5e0f1c6817899e4447&redirect_uri=https://beta.coyno.com/addcoinbase&response_type=code&scope=user+addresses"
    }
  ],
  unavailableExchanges: [
    {
      type: 'kraken',
      label: 'Kraken'
    },  {
      type: 'bitstamp',
      label: 'Bitstamp'
    },  {
      type: 'btcchina',
      label: 'BTCChina'
    },    {
      type: 'okcoin',
      label: 'OKCoin'
    },    {
      type: 'huobi',
      label: 'Huobi'
    },    {
      type: 'bitfinex',
      label: 'Bitfinex'
    },  {
      type: 'btc-e',
      label: 'BTC-e'
    },  {
      type: 'cryptsy',
      label: 'Cryptsy'
    },  {
      type: 'bitcoinde',
      label: 'Bitcoin.de'
    },  {
      type: 'circle',
      label: 'Circle'
    }
  ],
  supportedHDWallets : supportedHDWallets,
  goneExchanges: [
    {
      type: 'mtgox',
      label: 'MtGox'
    }
  ],
  supportedBitcoinWalletTypes: ['bitcoin-wallet', 'electrum', 'armory', 'trezor', 'mycelium', 'coinbase', 'single-addresses', 'electrum2'],
  supportedNodeTypes: ['bitcoinwallet', 'bitcoinaddress', 'exchange'],
  availableWallets: supportedHDWallets.concat([{
      type: 'single-addresses',
      label: 'Single Addresses'
    }
  ]),
  availableHybridWallets: [
    {
      type: 'coinbase',
      label: 'Coinbase'
    }
  ],
  unavailableWallets: [
    {
      type: 'blockchaininfo',
      label: 'Blockchain.info'
    },  {
      type: 'multibit',
      label: 'MultiBit'
    }, {
      type: 'green-address-wallet',
      label: 'Green Address'
    }, {
      type: 'hive-wallet',
      label: 'Hive'
    }, {
      type: 'breadwallet',
      label: 'Bread Wallet'
    }, {
      type: 'kncwallet',
      label: 'KnC'
    }, {
      type: 'msigna',
      label: 'mSigna'
    }, {
      type: 'xapo',
      label: 'Xapo'
    },  {
      type: 'ledger',
      label: 'Ledger'
    }, {
      type: 'coinkite',
      label: 'Coinkite'
    }
  ]
};
// ---
// generated by coffee-script 1.9.0
